"""
Authentication middleware for validating requests from API Gateway.

Except for explicit health and metrics probes, every request must carry the
short-lived HMAC envelope generated by a trusted API Gateway proxy Lambda. The
envelope binds the signature version, timestamp, random nonce, HTTP method,
exact path and query string, and SHA-256 body digest. The middleware validates
freshness and integrity and rejects process-local nonce replays.

Security Flow:
    1. API Gateway validates client IAM credentials (SigV4)
    2. Lambda signs the exact backend request with the shared signing key
    3. This middleware validates the HMAC envelope and consumes its nonce
    4. Invalid, stale, tampered, or replayed envelopes result in 403 Forbidden

Secret Rotation Support:
    During rotation, signatures are validated against both AWSCURRENT and
    AWSPENDING signing keys for zero-downtime rotation. Successful refreshes
    are cached with a bounded stale grace period; expired caches fail closed.

Environment Variables:
    AUTH_SECRET_ARN: ARN of the Secrets Manager secret containing the signing key
    GCO_DEV_MODE: Set to "true" to allow unauthenticated requests when no
        secret is configured. Without this flag, missing AUTH_SECRET_ARN
        causes 503 errors (fail-closed). This prevents accidental
        unauthenticated deployments due to misconfiguration.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import re
import threading
import time
from collections.abc import Awaitable, Callable
from typing import Any

import boto3
from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import JSONResponse, Response
from starlette.types import ASGIApp

# <pyflowchart-code-diagram> BEGIN - auto-inserted, do not edit
# Generated at (UTC): 2026-09-01T14:42:56Z
# Generated from Git commit: 89b000378ed5a912a38c06f4feab2b029936ebcc
# Flowchart(s) generated from this file:
#   * ``AuthenticationMiddleware.dispatch`` -> ``diagrams/code_diagrams/gco/services/auth_middleware.AuthenticationMiddleware_dispatch.html``
#     (PNG: ``diagrams/code_diagrams/gco/services/auth_middleware.AuthenticationMiddleware_dispatch.png``)
# Regenerate with ``SOURCE_DATE_EPOCH=<unix-seconds> GCO_DIAGRAM_SOURCE_COMMIT=<40-char-sha> python diagrams/generate.py --code-only``.
# <pyflowchart-code-diagram> END


logger = logging.getLogger(__name__)

# Module-level cache for secret signing keys and replay nonces.
_cached_tokens: set[str] = set()
_token_expirations: dict[str, float] = {}
_cache_timestamp = 0.0
_last_successful_refresh = 0.0
_last_refresh_attempt = 0.0
_secrets_client = None
_nonce_lock = threading.Lock()
_seen_nonces: dict[str, float] = {}
_NONCE_PATTERN = re.compile(r"^[0-9a-f]{32}$")


def _bounded_env_float(name: str, default: float, minimum: float, maximum: float) -> float:
    try:
        value = float(os.getenv(name, str(default)))
    except ValueError:
        return default
    return value if minimum <= value <= maximum else default


CACHE_TTL_SECONDS = _bounded_env_float("AUTH_CACHE_TTL_SECONDS", 300.0, 1.0, 3600.0)
CACHE_MAX_STALE_SECONDS = max(
    CACHE_TTL_SECONDS,
    _bounded_env_float("AUTH_CACHE_MAX_STALE_SECONDS", 900.0, 1.0, 7200.0),
)
CACHE_RETRY_SECONDS = _bounded_env_float("AUTH_CACHE_RETRY_SECONDS", 5.0, 0.1, 60.0)
SIGNATURE_MAX_AGE_SECONDS = _bounded_env_float("AUTH_SIGNATURE_MAX_AGE_SECONDS", 30.0, 5.0, 300.0)
_MAX_TRACKED_NONCES = 10_000

# Endpoints that bypass authentication (health checks for load balancers and
# Global Accelerator). /api/v1/health is included so GA can perform HTTP
# health checks for intelligent routing without an HMAC envelope.
UNAUTHENTICATED_PATHS = frozenset(["/healthz", "/readyz", "/metrics", "/api/v1/health"])


def get_secrets_client() -> Any:
    """
    Get Secrets Manager client with lazy initialization.

    The client is configured to use the region from the AUTH_SECRET_ARN
    environment variable, which may be different from the default region.

    Returns:
        boto3 Secrets Manager client instance
    """
    global _secrets_client
    if _secrets_client is None:
        # Extract region from the secret ARN
        # Format: arn:aws:secretsmanager:REGION:ACCOUNT:secret:NAME
        secret_arn = os.environ.get("AUTH_SECRET_ARN", "")
        region = None
        if secret_arn:
            parts = secret_arn.split(":")
            if len(parts) >= 4:
                region = parts[3]
        _secrets_client = boto3.client("secretsmanager", region_name=region)
    return _secrets_client


def _is_cache_valid() -> bool:
    """Return whether keys are still inside the normal refresh TTL."""
    return bool(_cached_tokens) and (time.monotonic() - _last_successful_refresh) < (
        CACHE_TTL_SECONDS
    )


def _previous_token_valid_until(secrets_client: Any, secret_arn: str) -> float | None:
    """Return the fixed AWSPREVIOUS deadline from rotation completion metadata.

    ``LastRotatedDate`` is set when Secrets Manager finishes rotation. Deriving
    the deadline from it prevents successful cache refreshes from renewing a
    displaced key indefinitely. Missing or malformed metadata fails closed for
    AWSPREVIOUS without making AWSCURRENT or AWSPENDING unavailable.
    """
    try:
        metadata = secrets_client.describe_secret(SecretId=secret_arn)
        last_rotated = metadata.get("LastRotatedDate")
        timestamp = getattr(last_rotated, "timestamp", None)
        if not callable(timestamp):
            raise ValueError("LastRotatedDate is missing")
        return float(timestamp()) + CACHE_MAX_STALE_SECONDS
    except Exception:
        logger.debug("AWSPREVIOUS rotation metadata is unavailable")
        return None


def _refresh_cache() -> bool:
    """Refresh current and overlap keys without extending stale lifetime on failure."""
    global _cached_tokens, _token_expirations
    global _cache_timestamp, _last_successful_refresh, _last_refresh_attempt

    secret_arn = os.environ.get("AUTH_SECRET_ARN")
    if not secret_arn:
        return False

    now = time.monotonic()
    _last_refresh_attempt = now
    try:
        secrets_client = get_secrets_client()
        response = secrets_client.get_secret_value(
            SecretId=secret_arn,
            VersionStage="AWSCURRENT",
        )
        secret_data = json.loads(response["SecretString"])
        current = secret_data.get("token")
        if not isinstance(current, str) or not current:
            raise ValueError("AWSCURRENT token is missing")
        new_tokens = {current}
        new_token_expirations: dict[str, float] = {}

        # Signers cache AWSCURRENT independently for up to
        # CACHE_MAX_STALE_SECONDS. During rotation, Secrets Manager moves the
        # displaced current version to AWSPREVIOUS, so validators must retain
        # both optional overlap stages while a warm signer can still use them.
        # AWSPREVIOUS gets a fixed wall-clock deadline from LastRotatedDate;
        # unlike the aggregate cache TTL, successful refreshes cannot renew it.
        for version_stage in ("AWSPENDING", "AWSPREVIOUS"):
            try:
                response = secrets_client.get_secret_value(
                    SecretId=secret_arn,
                    VersionStage=version_stage,
                )
                overlap_data = json.loads(response["SecretString"])
                overlap = overlap_data.get("token")
                if not isinstance(overlap, str) or not overlap:
                    continue
                if version_stage == "AWSPREVIOUS" and overlap not in new_tokens:
                    valid_until = _previous_token_valid_until(secrets_client, secret_arn)
                    if valid_until is None or time.time() > valid_until:
                        logger.info("AWSPREVIOUS signing key is outside its overlap window")
                        continue
                    new_token_expirations[overlap] = valid_until
                new_tokens.add(overlap)
            except secrets_client.exceptions.ResourceNotFoundException:
                pass
            except Exception:
                logger.debug("%s signing key is unavailable", version_stage)
    except Exception:
        logger.exception("Failed to refresh authentication signing keys")
        return False

    _cached_tokens = new_tokens
    _token_expirations = new_token_expirations
    _last_successful_refresh = now
    _cache_timestamp = now
    logger.info("Authentication signing-key cache refreshed")
    return True


def get_valid_tokens() -> set[str]:
    """Return current signing keys with a strictly bounded stale grace period."""
    now = time.monotonic()
    if not _is_cache_valid() and now - _last_refresh_attempt >= CACHE_RETRY_SECONDS:
        _refresh_cache()
    age = time.monotonic() - _last_successful_refresh
    if _cached_tokens and age <= CACHE_MAX_STALE_SECONDS:
        wall_clock = time.time()
        return {
            token
            for token in _cached_tokens
            if token not in _token_expirations or wall_clock <= _token_expirations[token]
        }
    return set()


def get_secret_token() -> str | None:
    """Return one primary signing key for compatibility callers.

    HMAC validation should use :func:`get_valid_tokens` so both current and
    pending rotation keys are considered.
    """
    tokens = get_valid_tokens()
    return next(iter(tokens), None) if tokens else None


def clear_token_cache() -> None:
    """Clear signing-key and replay caches, forcing a refresh."""
    global _cached_tokens, _token_expirations
    global _cache_timestamp, _last_successful_refresh, _last_refresh_attempt
    _cached_tokens = set()
    _token_expirations = {}
    _cache_timestamp = 0.0
    _last_successful_refresh = 0.0
    _last_refresh_attempt = 0.0
    with _nonce_lock:
        _seen_nonces.clear()
    logger.info("Authentication signing-key cache cleared")


def _request_target(request: Request) -> str:
    raw_path = request.scope.get("raw_path")
    path = raw_path.decode("latin-1") if isinstance(raw_path, bytes) else request.url.path
    raw_query = request.scope.get("query_string", b"")
    query = raw_query.decode("latin-1") if isinstance(raw_query, bytes) else str(raw_query)
    return path + (f"?{query}" if query else "")


def _accept_nonce(nonce: str, now: float) -> bool:
    """Reject process-local replays and keep the nonce cache strictly bounded."""
    expires_at = now + SIGNATURE_MAX_AGE_SECONDS
    with _nonce_lock:
        expired = [key for key, expiry in _seen_nonces.items() if expiry < now]
        for key in expired:
            _seen_nonces.pop(key, None)
        if nonce in _seen_nonces:
            return False
        if len(_seen_nonces) >= _MAX_TRACKED_NONCES:
            oldest = min(_seen_nonces, key=_seen_nonces.__getitem__)
            _seen_nonces.pop(oldest, None)
        _seen_nonces[nonce] = expires_at
    return True


async def _has_valid_signature(request: Request, signing_keys: set[str]) -> bool:
    """Validate the short-lived HMAC envelope added by the trusted Lambda."""
    headers = request.headers
    if headers.get("x-gco-signature-version") != "v1":
        return False
    signature = headers.get("x-gco-signature", "")
    timestamp_value = headers.get("x-gco-timestamp", "")
    nonce = headers.get("x-gco-nonce", "")
    claimed_content_hash = headers.get("x-gco-content-sha256", "")
    if (
        len(signature) != 64
        or len(claimed_content_hash) != 64
        or _NONCE_PATTERN.fullmatch(nonce) is None
    ):
        return False
    try:
        timestamp = int(timestamp_value)
    except ValueError:
        return False
    now = time.time()
    if abs(now - timestamp) > SIGNATURE_MAX_AGE_SECONDS:
        return False

    body = await request.body()
    actual_content_hash = hashlib.sha256(body).hexdigest()
    if not hmac.compare_digest(actual_content_hash, claimed_content_hash):
        return False
    canonical = "\n".join(
        [
            "v1",
            timestamp_value,
            nonce,
            request.method.upper(),
            _request_target(request),
            actual_content_hash,
        ]
    )
    valid = any(
        hmac.compare_digest(
            signature,
            hmac.new(
                key.encode("utf-8"),
                canonical.encode("utf-8"),
                hashlib.sha256,
            ).hexdigest(),
        )
        for key in signing_keys
    )
    return valid and _accept_nonce(nonce, now)


class AuthenticationMiddleware(BaseHTTPMiddleware):
    """Validate the API Gateway proxy's short-lived HMAC request envelope.

    Health-check endpoints are excluded for load balancer probes. During key
    rotation, signatures from both AWSCURRENT and AWSPENDING are accepted.
    """

    def __init__(self, app: ASGIApp) -> None:
        super().__init__(app)
        # Startup-time configuration check — surface misconfigurations early
        secret_arn = os.environ.get("AUTH_SECRET_ARN")
        if not secret_arn:
            dev_mode = os.environ.get("GCO_DEV_MODE", "").lower() == "true"
            if dev_mode:
                logger.warning(
                    "GCO_DEV_MODE=true with no AUTH_SECRET_ARN — "
                    "authentication is bypassed. Do NOT use in production."
                )
            else:
                logger.error(
                    "AUTH_SECRET_ARN is not configured and GCO_DEV_MODE is not enabled. "
                    "All non-health-check requests will be denied with 503."
                )

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        """
        Process incoming request and validate authentication.

        Args:
            request: The incoming FastAPI request
            call_next: The next middleware/handler in the chain

        Returns:
            Response from the next handler, or a bounded JSON authentication error.
        """
        # Skip authentication for health check endpoints
        if request.url.path in UNAUTHENTICATED_PATHS:
            return await call_next(request)

        valid_tokens = get_valid_tokens()

        # No tokens available — determine whether to fail open or closed
        if not valid_tokens:
            secret_arn = os.environ.get("AUTH_SECRET_ARN")
            if not secret_arn:
                # No secret configured. Only allow requests if the operator
                # explicitly opted into dev mode. This prevents accidental
                # unauthenticated deployments due to misconfiguration.
                dev_mode = os.environ.get("GCO_DEV_MODE", "").lower() == "true"
                if dev_mode:
                    logger.warning(
                        "Authentication bypassed - GCO_DEV_MODE=true, no secret configured"
                    )
                    return await call_next(request)
                # Fail closed: no secret + no dev mode = deny
                logger.error(
                    "No AUTH_SECRET_ARN configured and GCO_DEV_MODE is not enabled. "
                    "Set AUTH_SECRET_ARN for production or GCO_DEV_MODE=true for local development."
                )
                return JSONResponse(
                    status_code=503,
                    content={"detail": "Service unavailable - authentication not configured"},
                )
            # Secret configured but couldn't load - deny access
            logger.error("Failed to load authentication tokens")
            return JSONResponse(
                status_code=503,
                content={"detail": "Service temporarily unavailable - authentication error"},
            )

        if not await _has_valid_signature(request, valid_tokens):
            client_ip = request.client.host if request.client else "unknown"
            logger.warning(
                "Invalid backend signature from %s for %s",
                client_ip,
                request.url.path,
            )
            return JSONResponse(
                status_code=403,
                content={
                    "detail": ("Forbidden - requests must come through authenticated API Gateway")
                },
            )

        return await call_next(request)
