#!/usr/bin/env python3
"""
Version bump script for GCO.

The authoritative version lives in the top-level ``VERSION`` file so that
shell scripts, Dockerfiles, and CI workflows can read it without importing
Python. This script keeps the release version and maintained exact-ref examples in sync:

- ``VERSION``                  (source of truth, plain text: ``MAJOR.MINOR.PATCH``)
- ``gco/_version.py``          (mirrors VERSION as ``__version__``)
- ``cli/__init__.py``          (fallback ``__version__`` when ``gco`` is not importable)
- ``gco_mcp/README.md``        (exact release refs in copy-paste MCP launch examples)
- ``README.md``                (one-click MCP install buttons whose deep links embed
                                the release ref URL-encoded and base64-encoded; the
                                whole marked block is regenerated, not regex-patched)

``gco._version.__version__`` reads its value at import time and should always
match ``VERSION`` on a clean checkout.

Other components that follow the same version automatically (no script
changes needed):

- ``gco_mcp/run_mcp.py``            imports ``gco._version.__version__`` for its
                                ``_MCP_SERVER_VERSION`` and reports it in the
                                startup audit log.
- ``pyproject.toml``            uses ``dynamic = ["version"]`` with
                                ``setuptools.dynamic.version`` set to
                                ``{attr = "gco._version.__version__"}``, so the
                                built wheel tracks the same value.

Usage:
    python scripts/bump_version.py major            # 0.0.9 -> 1.0.0
    python scripts/bump_version.py minor            # 0.0.9 -> 0.1.0
    python scripts/bump_version.py patch            # 0.0.9 -> 0.0.10
    python scripts/bump_version.py patch --dry-run  # Show what would change
    python scripts/bump_version.py                  # Show current version
"""

import base64
import json
import re
import sys
import urllib.parse
from pathlib import Path

# File paths relative to project root
PROJECT_ROOT = Path(__file__).parent.parent
VERSION_FILE = PROJECT_ROOT / "VERSION"
VERSION_PY = PROJECT_ROOT / "gco" / "_version.py"
CLI_INIT_FILE = PROJECT_ROOT / "cli" / "__init__.py"
MCP_README_FILE = PROJECT_ROOT / "gco_mcp" / "README.md"
ROOT_README_FILE = PROJECT_ROOT / "README.md"

# Markers delimiting the auto-generated one-click MCP install table in the
# top-level README. Everything between them is owned by this script.
MCP_INSTALL_TABLE_BEGIN = (
    "<!-- BEGIN MCP INSTALL TABLE (generated by scripts/bump_version.py; edit there) -->"
)
MCP_INSTALL_TABLE_END = "<!-- END MCP INSTALL TABLE -->"

REPO_GIT_URL = (
    "https://github.com/aws-solutions-library-samples/global-capacity-orchestrator-on-aws.git"
)


def _mcp_server_config(version: str) -> dict[str, str | list[str]]:
    """Canonical one-click install config for the GCO MCP server.

    Mirrors the recommended clone-free ``uvx`` form documented in
    gco_mcp/README.md, pinned to the exact release ref.
    """
    return {
        "command": "uvx",
        "args": [
            "--python",
            "3.14",
            "--from",
            f"git+{REPO_GIT_URL}@v{version}",
            "gco-mcp",
        ],
    }


def render_mcp_install_table(version: str) -> str:
    """Render the one-click MCP install table for the top-level README.

    Deep-link formats follow https://github.com/awslabs/mcp: Kiro and
    VS Code take the URL-encoded server-config JSON, Cursor takes it
    base64-encoded.
    """
    config = _mcp_server_config(version)
    compact = json.dumps(config, separators=(",", ":"))
    url_encoded = urllib.parse.quote(compact, safe="")
    b64_encoded = base64.b64encode(compact.encode("utf-8")).decode("ascii")

    kiro_href = f"https://kiro.dev/launch/mcp/add?name=gco&config={url_encoded}"
    cursor_href = f"https://cursor.com/en/install-mcp?name=gco&config={urllib.parse.quote(b64_encoded, safe='')}"
    vscode_href = f"https://insiders.vscode.dev/redirect/mcp/install?name=gco&config={url_encoded}"

    return "\n".join(
        [
            MCP_INSTALL_TABLE_BEGIN,
            "<table>",
            "  <tr>",
            '    <th><a href="https://kiro.dev/docs/mcp/">Kiro</a></th>',
            '    <th><a href="https://cursor.com/docs/context/mcp">Cursor</a></th>',
            '    <th><a href="https://code.visualstudio.com/docs/copilot/chat/mcp-servers">VS Code</a></th>',
            "  </tr>",
            "  <tr>",
            f'    <td><a href="{kiro_href}"><img src="https://kiro.dev/images/add-to-kiro.svg" alt="Add to Kiro"></a></td>',
            f'    <td><a href="{cursor_href}"><img src="https://cursor.com/deeplink/mcp-install-light.svg" alt="Add to Cursor"></a></td>',
            f'    <td><a href="{vscode_href}"><img src="https://img.shields.io/badge/Install_on-VS_Code-FF9900?style=flat-square" alt="Install on VS Code" height="28"></a></td>',
            "  </tr>",
            "</table>",
            MCP_INSTALL_TABLE_END,
        ]
    )


def get_version() -> str:
    """Read current version from the top-level VERSION file."""
    if not VERSION_FILE.exists():
        raise FileNotFoundError(
            f"VERSION file not found at {VERSION_FILE.relative_to(PROJECT_ROOT)}. "
            "Create it with a single line of the form MAJOR.MINOR.PATCH."
        )
    version = VERSION_FILE.read_text().strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise ValueError(
            f"Invalid version in {VERSION_FILE.relative_to(PROJECT_ROOT)}: {version!r}. "
            "Expected MAJOR.MINOR.PATCH."
        )
    return version


def update_version_file(version: str, dry_run: bool = False) -> None:
    """Update the top-level VERSION file."""
    if dry_run:
        print(f"  [dry-run] Would update {VERSION_FILE.relative_to(PROJECT_ROOT)}")
        return
    VERSION_FILE.write_text(f"{version}\n")
    print(f"  ✓ Updated {VERSION_FILE.relative_to(PROJECT_ROOT)}")


def update_version_py(version: str, dry_run: bool = False) -> None:
    """Update ``__version__`` in gco/_version.py."""
    if dry_run:
        print(f"  [dry-run] Would update {VERSION_PY.relative_to(PROJECT_ROOT)}")
        return
    content = VERSION_PY.read_text()
    new_content = re.sub(
        r'__version__\s*=\s*["\'][^"\']+["\']',
        f'__version__ = "{version}"',
        content,
    )
    VERSION_PY.write_text(new_content)
    print(f"  ✓ Updated {VERSION_PY.relative_to(PROJECT_ROOT)}")


def update_cli_init(version: str, dry_run: bool = False) -> None:
    """Update fallback ``__version__`` in cli/__init__.py."""
    if dry_run:
        print(f"  [dry-run] Would update {CLI_INIT_FILE.relative_to(PROJECT_ROOT)}")
        return
    content = CLI_INIT_FILE.read_text()
    new_content = re.sub(
        r'__version__\s*=\s*["\'][^"\']+["\']',
        f'__version__ = "{version}"',
        content,
        flags=re.MULTILINE,
    )
    CLI_INIT_FILE.write_text(new_content)
    print(f"  ✓ Updated {CLI_INIT_FILE.relative_to(PROJECT_ROOT)}")


def update_mcp_readme_release_refs(version: str, dry_run: bool = False) -> None:
    """Update exact release refs in copy-paste MCP launch examples."""
    if dry_run:
        print(f"  [dry-run] Would update {MCP_README_FILE.relative_to(PROJECT_ROOT)}")
        return
    content = MCP_README_FILE.read_text(encoding="utf-8")
    new_content = re.sub(r"@v\d+\.\d+\.\d+", f"@v{version}", content)
    new_content = re.sub(
        r"(?m)^GCO_REF=v\d+\.\d+\.\d+",
        f"GCO_REF=v{version}",
        new_content,
    )
    MCP_README_FILE.write_text(new_content, encoding="utf-8")
    print(f"  ✓ Updated {MCP_README_FILE.relative_to(PROJECT_ROOT)}")


def update_root_readme_install_table(version: str, dry_run: bool = False) -> None:
    """Regenerate the one-click MCP install table in the top-level README.

    The Kiro/VS Code deep links embed the release ref URL-encoded and the
    Cursor deep link embeds it base64-encoded, so a plain ``@vX.Y.Z`` regex
    can't reach them. Instead this script owns the whole marked block and
    rewrites it wholesale from :func:`render_mcp_install_table`.
    """
    if dry_run:
        print(f"  [dry-run] Would update {ROOT_README_FILE.relative_to(PROJECT_ROOT)}")
        return
    content = ROOT_README_FILE.read_text(encoding="utf-8")
    begin = content.find(MCP_INSTALL_TABLE_BEGIN)
    end = content.find(MCP_INSTALL_TABLE_END)
    if begin == -1 or end == -1 or end < begin:
        raise ValueError(
            f"MCP install table markers not found in "
            f"{ROOT_README_FILE.relative_to(PROJECT_ROOT)}; expected "
            f"{MCP_INSTALL_TABLE_BEGIN!r} … {MCP_INSTALL_TABLE_END!r}."
        )
    new_content = (
        content[:begin]
        + render_mcp_install_table(version)
        + content[end + len(MCP_INSTALL_TABLE_END) :]
    )
    ROOT_README_FILE.write_text(new_content, encoding="utf-8")
    print(f"  ✓ Updated {ROOT_README_FILE.relative_to(PROJECT_ROOT)}")


def bump_version(bump_type: str) -> str:
    """Bump version based on type (major, minor, patch)."""
    current = get_version()
    major, minor, patch = (int(p) for p in current.split("."))

    if bump_type == "major":
        major += 1
        minor = 0
        patch = 0
    elif bump_type == "minor":
        minor += 1
        patch = 0
    elif bump_type == "patch":
        patch += 1
    else:
        raise ValueError(f"Invalid bump type: {bump_type}")

    return f"{major}.{minor}.{patch}"


def set_version(version: str, dry_run: bool = False) -> None:
    """Update the source version, Python mirrors, and documented launch refs."""
    action = "Would update" if dry_run else "Updating"
    print(f"\n{action} version to {version}:")
    update_version_file(version, dry_run)
    update_version_py(version, dry_run)
    update_cli_init(version, dry_run)
    update_mcp_readme_release_refs(version, dry_run)
    update_root_readme_install_table(version, dry_run)


def main() -> None:
    args = [a.lower() for a in sys.argv[1:]]
    dry_run = "--dry-run" in args or "-n" in args
    args = [a for a in args if a not in ("--dry-run", "-n")]

    if len(args) < 1:
        print(f"Current version: {get_version()}")
        print("\nVersion locations:")
        print(f"  - {VERSION_FILE.relative_to(PROJECT_ROOT)}  (source of truth)")
        print(f"  - {VERSION_PY.relative_to(PROJECT_ROOT)}")
        print(f"  - {CLI_INIT_FILE.relative_to(PROJECT_ROOT)}")
        print(f"  - {MCP_README_FILE.relative_to(PROJECT_ROOT)}  (MCP launch refs)")
        print(f"  - {ROOT_README_FILE.relative_to(PROJECT_ROOT)}  (MCP install buttons)")
        return

    bump_type = args[0]
    if bump_type not in ("major", "minor", "patch"):
        print(f"Usage: {sys.argv[0]} [major|minor|patch] [--dry-run]")
        sys.exit(1)

    old_version = get_version()
    new_version = bump_version(bump_type)
    set_version(new_version, dry_run)

    if dry_run:
        print(f"\n[dry-run] Would bump version: {old_version} -> {new_version}")
    else:
        print(f"\n✓ Bumped version: {old_version} -> {new_version}")
        print("\nTo complete the release PR:")
        print("  git add VERSION gco/_version.py cli/__init__.py gco_mcp/README.md README.md")
        print(f"  git commit -m 'Release v{new_version}'")
        print("  git push -u origin HEAD")
        print(
            f"  gh pr create --base main --title 'Release v{new_version}' "
            "--body 'Version bump; release-publish.yml tags the reviewed merge.'"
        )
        print("\nAfter review, squash-merge the PR; release-publish.yml creates the tag.")


if __name__ == "__main__":
    main()
